---
title: "STAT_574_Regression_Trees"
output: html_notebook
---

```{r}
install.packages("rpart")
install.packages("rpart.plot")
install.packages("dplyr")
install.packages("partykit")
install.packages("CHAID",repos="http://R-Forge.R-project.org", type="source")

library(readr)
library(rpart)
library(rpart.plot)
library(partykit)
library(CHAID)
library(dplyr)
```

```{r}
housing.data = read.csv(file="C:/Users/coryg/OneDrive/Desktop/STAT_574_Data_Mining/housing_data.csv", header=T, sep=",")

#Splitting data into 80% training and 20% testing

set.seed(105388)
sample = sample(c(T,F), nrow(housing.data), replace=T, prob=c(0.8,0.2))
train = housing.data[sample,]
test = housing.data[!sample,]

#Fitting full regression tree with RSS Splitting

reg.tree.full = rpart(median_house_value~housing_median_age+total_rooms+total_bedrooms+population+
households+median_income+ocean_proximity, data=train, method="anova", xval=10, cp=0)

printcp(reg.tree.full)
```

```{r}

#Fitting regression tree with RSS Splitting and Cost-Complexity Pruning

reg.tree.RSS = rpart(median_house_value~housing_median_age+total_rooms+total_bedrooms+population+
households+median_income+ocean_proximity, data=train, method="anova", xval=10, cp=0.026)

rpart.plot(reg.tree.RSS, type=3)

#Computing prediction accuracy with test data

P_median_house_value = predict(reg.tree.RSS, newdata=test)

#Accuracy within 10%

accuracy10 = ifelse(abs(test$median_house_value-P_median_house_value)<0.10*test$median_house_value,1,0)
print(mean(accuracy10))

#Accuracy within 15%
accuracy15 = ifelse(abs(test$median_house_value-P_median_house_value)<0.15*test$median_house_value,1,0)
print(mean(accuracy15))

#Accuracy within 20%

accuracy20 = ifelse(abs(test$median_house_value-P_median_house_value)<0.20*test$median_house_value,1,0)
print(mean(accuracy20))
```

```{r}

#Fitting regression tree with CHAID Splitting Criterion and Cost-Complexity Pruning

#Binning continuous predictor variables

housing.data = mutate(housing.data, housing_median_age_cat=ntile(housing_median_age,10),
total_rooms_cat=ntile(total_rooms,10), total_bedrooms_cat=ntile(total_bedrooms,10),
population_cat=ntile(population,10), households_cat=ntile(households,10),
median_income_cat=ntile(median_income,10), median_house_value_cat=ntile(median_house_value,10))

#Splitting data into 80% training and 20% testing

set.seed(105388)
sample = sample(c(T,F), nrow(housing.data), replace=T, prob=c(0.8,0.2))
train = housing.data[sample,]
test = housing.data[!sample,]

reg.tree.CHAID = chaid(as.factor(median_house_value_cat)~as.factor(housing_median_age_cat)+
as.factor(total_rooms_cat)+as.factor(total_bedrooms_cat)+as.factor(population_cat)+
as.factor(households_cat)+as.factor(median_income_cat)+as.factor(ocean_proximity),
data=train, control=chaid_control(maxheight=4))

plot(reg.tree.CHAID, type="simple")

#Computing prediction accuracy for testing data

pred_class = as.numeric(predict(reg.tree.CHAID, newdata=test))
test = cbind(test, pred_class)

aggr.data = aggregate(train$median_house_value, by=list(train$median_house_value_cat), FUN=mean)

aggr.data$pred_class = aggr.data$Group.1
aggr.data$P_median_house_value = aggr.data$x
test = left_join(test, aggr.data, by='pred_class')

#Accuracy within 10%

accuracy10 = ifelse(abs(test$median_house_value-P_median_house_value)<0.10*test$median_house_value,1,0)
print(mean(accuracy10))

#Accuracy within 15%
accuracy15 = ifelse(abs(test$median_house_value-P_median_house_value)<0.15*test$median_house_value,1,0)
print(mean(accuracy15))

#Accuracy within 20%

accuracy20 = ifelse(abs(test$median_house_value-P_median_house_value)<0.20*test$median_house_value,1,0)
print(mean(accuracy20))
```
